import Head from "next/head";
import estilos from "@/styles/Home.module.css";



export default function Home() {
  return (
    <div clasName={estilos.container_principal}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={estilos.container_texto}>
        <h1>Hello World</h1>
        <p>Paragrafo com React.js</p>
        <p className={estilos.autor}>Criado por André</p>
      </div>


    </div>
  );
}
